services:
  test:
    image: "exercise_1"
    environment:
      - PYTHONPATH=/usr/local/exercise_1
    volumes:
      - .:/usr/local/exercise_1
    command: python -m pytest
  
  run:
    image: "exercise_1"
    environment:
      - PYTHONPATH=/usr/local/exercise_1
    volumes:
    #  - ./downloads:/usr/local/exercise_1/downloads
    #  - ./logs:/usr/local/exercise_1/logs
       - .:/usr/local/exercise_1
    command: python app.py